### PR TITLE
Dom elements

### PR DESCRIPTION
**Pull request by SMITHsharon**
@justinal64
This is an intermediate Pull Request. 
Stuck on the last piece, the text-editing piece for the Person Bio. 
Looks like I could use a conversation. Or something.

### CODE REVIEW

**Comment by justinal64** [comment]
@SMITHsharon Hit me up on slack if you want to work through the problem. I got stuck at the exact same place as you are when I was working on this project.

**Comment by SMITHsharon** [comment]
@justinal64 
done! #woot! #totally;)

**Comment by justinal64** [comment]
@SMITHsharon I'm getting this error in the console.
```
Error in event handler for (unknown): SyntaxError: Failed to execute 'addRule' on 'CSSStyleSheet': Failed to parse the rule '::content .site-footer__ad-area, ::content .sponlinkbox, ::content .sponsoredLeft, ::content .staticAd, ::content .td_footer_ads, ::content .top-ad-anchor, ::content .topadblock, ::content .variableHeightAd, ::content .wide-ad-outer, ::content .wnIframeAd, ::content [onclick^="window.open('http://adultfriendfinder.com/search/"], ::content a[href^="http://fsoft4down.com/"], ::content a[href^="http://www.graboid.com/affiliates/"], ::content .rec-sponsored, ::content #AD_half, ::content #Ad_976x105, ::content #CompanyDetailsNarrowGoogleAdsPresentationControl, ::content #LS-google-ad, ::content #ad-300x40-2, ::content #ad-discover, ::content #ad-other, ::content #ad-top-left, ::content #ad728Header, ::content #adHolder6, ::content #adSpace17, ::content #ad_300x250, ::content #ad_body, ::content #ad_island2, ::content #ad_rightSidebarSecondBanner, ::content #ad_x20, ::content #add_block_ad2, ::content #adposition-inner-REM1, ::content #ads-top, ::content #ads_bottom_outer, ::content #adsense-sidebar, ::content #adspecial_offer_box, ::content #adv-left, ::content #advert-box, ::content #advertisementBox, ::content #adwrap-295x295, ::content #article_banner_ad, ::content #banner_mpu3, ::content #block-openx-1, ::content #bottom_ads, ::content #cbz-ads-text-link, ::content #contentAdTwo, ::content #ctl00_MainContent_adDiv2, ::content #desktop-unrec-ad, ::content #dfrads-widget-7, ::content #footAds, ::content #gallery_header_ad, ::content #googlead-left, ::content #headerAds4, ::content #homepage_top_ad, ::content #insider_ad_wrapper, ::content #lowerAdvertisement, ::content #midAD, ::content #my-adsLREC, ::content #p2HeaderAd, ::content #premium_ad, ::content #rh-ad-container, ::content #righttop-adverts-container, ::content #show-ad, ::content #sidebaradpane, ::content #sponsor-flyout-wrap, ::content #squareAdWrap, ::content #textlink-advertisement, ::content #top_ad_parent, ::content #under_content_ad, ::content #wide-ad, ::content .ADCLOUD, ::content .Ad_container, ::content .HPNewAdsBannerDiv, ::content .SkyscraperAD-border, ::content .ad-120-60, ::content .ad-banner-label, ::content .ad-diver, ::content .ad-link-right, ::content .ad-right1, ::content .ad-topbanner, ::content .ad300X250, ::content .adBar, ::content .adSkyscaper, ::content .ad_320x250_async, ::content .ad_break_container, ::content .ad_label_method, ::content .ad_skyscraper, ::content .adblock-bottom, ::content .adfoot, ::content .adpost, ::content .ads-leaderboard-panel, ::content .ads720x90, ::content .ads_column, ::content .adsbygoogle-box, ::content .adserve_728, ::content .adtech-banner, ::content .advText, ::content .advert_small, ::content .advertisement_article_right_middle2_computer, ::content .advt, ::content .artAd, ::content .badxcn, ::content .base_printer_widgets_AdBreak, ::content .block-fcc-advertising, ::content .bottom-game-ad, ::content .br-banner-ad, ::content .cdo-dicthomepage-btm-ad, ::content .companion-ads, ::content .ct-ad-article-wrapper, ::content .divAdsLeft, ::content .entryAd, ::content .footerAdUnit, ::content .gallery_300x100_ad, ::content .googleAdFoot, ::content .guide-ad, ::content .highlightsAd, ::content .hp_ad_box, ::content .inline_ad_container, ::content .jw-ad-visible, ::content .leftPaneAd, ::content .mainAds, ::content .midad, ::content .mp-ad, ::content .new-ad-box, ::content .outermainadtd1, ::content .pfimgAds, ::content .printAds, ::content .reedwan_adds300x250_widget, ::content .rightAdContainer, ::content .s-ad, ::content .showcasead, ::content .sidebar_ad_holder, ::content .small-ad-header, ::content .sponsor_div_title, ::content .sponsorshipContainer, ::content .superscroll-ad, ::content .the_list_ad_zone, ::content .topAdvertisement, ::content .ttlAdsensel, ::content .views-field-field-adbox-1, ::content .widget_advertisment, ::content .y5_ads, ::content a[href^="http://aflrm.com/"], ::content a[href^="http://t.mdn2015x3.com/"], ::content a[href^="https://understandsolar.com/signup/?lead_source="][href*=&tracking_code="], ::content #rhs_block > .ts[cellspacing="0"][cellpadding="0"][style="padding:0"], ::content #AdDisclaimer, ::content #AdvFooter, ::content #GOOGLE_ADS_2, ::content #RightAdvertisement, ::content #ad-1, ::content #ad-below-content, ::content #ad-sidebar-right_300-3, ::content #ad2_footer, ::content #adCirc300X200, ::content #adPosition7, ::content #adTopBanner-inner, ::content #ad_M, ::content #ad_feedback, ::content #ad_mpuslot, ::content #ad_spotlight, ::content #adbn_UMU, ::content #adlargeverti, ::content #ads-K, ::content #adsDiv1, ::content #ads_td, ::content #adsider, ::content #adtags_left, ::content #adv_98, ::content #advert_561_05, ::content #advertising_holder, ::content #amsSparkleAdWrapper, ::content #banner-ad-square-last, ::content #bigad300outer, ::content #boxtube-ad, ::content #commentTopAd, ::content #contentarea-ad, ::content #ctl_bottom_ad, ::content #dfp-ad-slot5, ::content #divBannerTopAds, ::content #f_ad, ::content #fp_rh_ad, ::content #head-ad-1, ::content #hly_inner_page_google_ad, ::content #im_popupDiv, ::content #js-image-ad-mpu, ::content #leftAdsSmall, ::content #mason_adv_bp_2, ::content #mpl_adv_text, ::content #nib-ad, ::content #player-below-advert, ::content #r_ad3_ad, ::content #right_ad_container, ::content #sidebar-ad-middle, ::content #skyscraperAds, ::content #sponsored_ads_v4, ::content #swfAd1, ::content #top-search-ad-wrapper, ::content #video_vert_right_ads, ::content #yahooSponsored { display: none !important; }'.
    at addElemHideSelectors (chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/include.preload.js:533:19)
    at checkLoaded (chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/include.preload.js:559:7)
    at chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/include.preload.js:575:7
    at CSSPropertyFilters.<anonymous> (chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/cssProperties.js:132:7)
``` 
I'm not sure who told you to use window.AddEventListener, but that adds an eventListener to the whole page and I don't think that is what you are looking for. It works when I click the proper area of the page, but if the user decides to click anywhere on the page the event fires as well. If you need any help between now and Saturday I'm on slack if you need me.

**Comment by SMITHsharon** [comment]
@justinal64 
fixed the error condition on the click

**Comment by justinal64** [comment]
👍 Looks great merge it in.

**Pull request merged**
